### ISSUE TITLE
Preparation of Input data and setting files for the LISVAP model reg.

### ISSUE THREAD

**Issue by diksha922** [ec-jrc/lisflood-lisvap#56]
Sir/ Madam,

I have to use the LISFLOOD-LISVAP model for the study area in Indian River basins at a daily time step for around 1o years.

Please help me out in preparing the input files for the LISVAP model. Can you please suggest me the sources for obtaining the input data for LISVSAP model and how to get the inputs from them in the format compatible with the LISVAP model?

**Comment by diksha922** [comment]
Sir/ Madam,

Please help me in rpeparing the input files for the LISVAP model and please suggest me the sources for obtaining the input data for LISVSAP model and how to get the inputs from them in the format compatible with the LISVAP model?

**Comment by gnrgomes** [comment]
Dear @diksha922 ,

Thank you for your interest in using LISVAP.
 
LISVAP computes reference values of evaporation and evapotranspiration using as input meteorological variables, a mask map, a digital elevation model, and a map with latitude values.
 
All the input maps must be in netcdf format, and they must have the same geographical extent (point of origin, number or rows, number of columns), the same resolution (that is, the pixel size), and the same coordinate system (one example is WGS84).
You can see the examples provided in the following folders https://github.com/ec-jrc/lisflood-lisvap/tree/master/basemaps/global
https://github.com/ec-jrc/lisflood-lisvap/tree/master/tests/data/input/glofas
 
The mask map is a Boolean map: all the pixels included in your study area have value 1. We recommend creating this map first and then using this map as template to prepare the digital elevation model, the latitude map, and the meteorological variables.
 
Regarding the meteorological variables, LISVAP can make use of different combinations of inputs. This allows to adjust to different scenarios of data availability, as explained here https://ec-jrc.github.io/lisflood-lisvap/3_1_LISVAP_setup/ . Some examples of application (EFAS, GloFAS, CORDEX) are available here https://github.com/ec-jrc/lisflood-lisvap/tree/master/tests/data
 
Therefore, we suggest that you select the most appropriate source of meteorological information for your own study area.
One example of freely available meteorological data set at the global scale is ERA5. In the frame of this example, LISVAP requires the following ERA5 variables:
10 metre U wind component, 10u, marsParam =165.128
10 metre V wind component, 10v, marsParam =166.128
2 metre temperature, 2t, marsParam =167.128
2 metre dewpoint temperature, 2d, marsParam =168.128
surface solar radiation downwards, ssrd, marsParam =169.128
surface thermal radiation, str, marsParam =177.128
 
What is the size and location of your study area?
If you deem it useful, we could help you to prepare the mask map (and, if we have all the data you need, the other LISVAP inputs).
We can provide you a mask map with 1 arcmin resolution within Europe, and with 3arcmin resolution in any other area of the globe.
To do so, we need the coordinates of the outlet point of your study area.
 
We hope our answer helps

**Comment by diksha922** [comment]
Thank you sir for the information.

It will be very kind of you if you could help me preparing the mask map as well as other LISVAP input files for my study area.

My study area is comprising of the three river basins in India i.e. Tapi, Godavari and Mahanadi basin.

Please help me in preparing the input files for these basins.

**Comment by gnrgomes** [comment]
Dear @diksha922 ,

We can provide you the mask map, the latitude map, and the digital elevation model for each one of your study area with 3 arcmin (or 0.05 degrees) resolution.
The coordinates of the outlets at 3 arcmin (or 0.05 degrees) resolution are:

- Tapi: Lon 72.725,  Lat 21.125
- Godavari: Lon 82.225, Lat 16.725
- Mahanadi: Lon 86.225,  Lat 20.275

Regarding the meteorological data, we recommend that you choose the meteorological dataset which is most suitable for your study area.
We can provide you the meteorological data that we have readily available, these are based on ERA5 (from 1979 to August 2022).

If our proposal suits your plans, could you please send an email to my colleague Stefania ( Stefania.GRIMALDI@ec.europa.eu )?
Since we cannot attach files in GitHub issues, she will cut the meteo input maps and share them with you.

We noticed that you are interested in running LISFLOOD, we would like to let you know that the static maps for LISFLOOD (global, 3arcmin resolution) will be publicly available in May.

Best regards.

**Comment by diksha922** [comment]
Hello @gnrgomes,

Thank you for the help.

I have dropped a mail to Stefania for the input mask files and meteorological files of LISVAP model. 

It is good to know that the static maps for LISFLOOD (global, 3arcmin resolution) will be publicly available in May. It will be very helpful in using LISFLOOD model.

Prompt response on providing the input files will be highly appreciated.

Thanks.
